FROM nvidia/cuda:8.0-cudnn5-devel

RUN apt-get update && apt-get install -y python-pip 
 
RUN pip install virtualenv==15.0.3
 
RUN virtualenv --system-site-packages /venv-cpu
RUN virtualenv --system-site-packages /venv-gpu
 
RUN chmod +x /venv-cpu/bin/activate
RUN chmod +x /venv-gpu/bin/activate
 
COPY ./requirements.txt /tmp/requirements.txt
 
RUN /venv-cpu/bin/pip install -r /tmp/requirements.txt
RUN /venv-gpu/bin/pip install -r /tmp/requirements.txt
 
ENV MY_TF_VER 1.1.0
RUN /venv-gpu/bin/pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-$MY_TF_VER-cp27-none-linux_x86_64.whl
RUN /venv-cpu/bin/pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-$MY_TF_VER-cp27-none-linux_x86_64.whl
